### ISSUE TITLE
Issues with Edit Button and Negative Offsets Display

### ISSUE THREAD

**Issue by Urahara3000** [BullyWiiPlaza/Universal-Pointer-Searcher#11]
Hi again my friend, I've been testing the new version of the program today, it's even better, however, I think I found 2 issues:

First issue: When I click the (Edit) button, the (Target Address) field and the (Confirm) button are disabled.

Below are 2 comparison images between version 3.5 and 3.8:

3.5 = https://tinyurl.com/yy9r94xj

3.8 = https://tinyurl.com/y6odwdmn

Second issue: When I look for routes with negative offsets, they no longer appear with the signal - before them.

Below are 2 comparison images between version 3.5 and 3.8:

3.5 = https://tinyurl.com/y4zm48rz

3.8 = https://tinyurl.com/y359czbb

From what I tested here, I think it was just these 2, stay with God and until next time.

**Comment by BullyWiiPlaza** [comment]
Hi again :)

For the first issue:
Can you try to untick the `Add Memory Dumps/Pointer Maps` checkbox?

For the second issue:
Can you try to select the `Offset Printing` as `Signed`?

**Comment by Urahara3000** [comment]
Oh, I didn't pay enough attention to these details, I'm sorry, I tested here and it worked out normally, thank you very much for the answer, stay with God and until next time.
