### ISSUE TITLE
Selection of the Dump file issue

### ISSUE THREAD

**Issue by Urahara3000** [BullyWiiPlaza/Universal-Pointer-Searcher#4]
The second issue is in the selection part of the Dump file, when I open the Dump file, a message appears below saying "Target address outside of memory dump bounds", not being outside, see the image below

https://drive.google.com/file/d/1nMsBDfvwd4iAtK49shUsXMELMGQt_zFd/view?usp=sharing

I would be very grateful if you could take a look at these issues

Thank you very much in advance !

**Comment by BullyWiiPlaza** [comment]
Yeah, that's quite easy. I will fix it later.
