### ISSUE TITLE
Add Memory Dumps Folder (Disabled)

### ISSUE THREAD

**Issue by Urahara3000** [BullyWiiPlaza/Universal-Pointer-Searcher#5]
I have already tested the new version, it is much better, I was able to analyze a dump of Cemu's Full RAM, in the other version was giving error with the 1 GB dump, however, the (Add Memory Dumps Folder) option is disabled, now I can no longer add an entire dumps folder, could you re-enable this option ?

**Comment by BullyWiiPlaza** [comment]
True, I messed this one up on the rewrite of the components availability code. Done.
